# Generated by Django 3.2 on 2021-04-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_question_bodyjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='bodyJson',
            field=models.JSONField(null=True),
        ),
    ]
