# Generated by Django 3.2 on 2021-04-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_question_bodyjson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='bodyJson',
        ),
    ]
