# Generated by Django 3.2 on 2021-04-28 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_question_bodyjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='timeOfBegin',
            field=models.DateTimeField(verbose_name='date publushed'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.question')),
            ],
        ),
    ]
