# Generated by Django 3.2 on 2021-04-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210428_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='bodyText',
        ),
    ]
