# Generated by Django 3.2 on 2021-04-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_question_bodytext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='polls',
        ),
        migrations.AddField(
            model_name='question',
            name='polls',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='article.poll'),
            preserve_default=False,
        ),
    ]
