# Generated by Django 3.2 on 2021-04-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20210428_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='polls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='article.poll'),
        ),
    ]
