# Generated by Django 3.2 on 2021-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_question_polls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='polls',
        ),
        migrations.AddField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(to='article.Question'),
        ),
    ]
