# Generated by Django 3.2 on 2021-04-28 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20210428_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='typeQ',
            field=models.CharField(choices=[('T', 'Text'), ('O', 'Select one'), ('S', 'Select_set')], default='T', max_length=1),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerIs', models.TextField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.question')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.respondent')),
            ],
        ),
    ]
